name: build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Install dependencies
        working-directory: generator
        run: go get .

      - name: Test
        working-directory: generator
        run: go test ./...

      - name: Build
        working-directory: generator
        run: go build -a -v